### ISSUE TITLE
Certain error types missing

### ISSUE THREAD

**Issue by stevezhu** [plaid/plaid-openapi#170]
Is this repo up to date?

It seems like some of the errors types such as the following aren't defined. These are the ones I've noticed:
https://plaid.com/docs/errors/virtual-account/
https://plaid.com/docs/errors/transactions/
https://plaid.com/docs/errors/transfer/
https://plaid.com/docs/errors/sandbox/
https://plaid.com/docs/errors/partner/

Only these are defined currently:
```yaml
    PlaidErrorType:
      title: PlaidErrorType
      type: string
      description: A broad categorization of the error. Safe for programmatic use.
      enum:
      - INVALID_REQUEST
      - INVALID_RESULT
      - INVALID_INPUT
      - INSTITUTION_ERROR
      - RATE_LIMIT_EXCEEDED
      - API_ERROR
      - ITEM_ERROR
      - ASSET_REPORT_ERROR
      - RECAPTCHA_ERROR
      - OAUTH_ERROR
      - PAYMENT_ERROR
      - BANK_TRANSFER_ERROR
      - INCOME_VERIFICATION_ERROR
      - MICRODEPOSITS_ERROR
```

At least the following are missing:
- TRANSACTION_ERROR
- TRANSACTIONS_ERROR
- TRANSFER_ERROR
- SANDBOX_ERROR
- PARTNER_ERROR
