### ISSUE TITLE
schemas with type:string has properties?

### ISSUE THREAD

**Issue by vamayufei** [plaid/plaid-openapi#174]
Hello there! Thanks for maintaining your docs. May I know why do some component schemas of type: string contain properties?

Here's an example:
```
    StandaloneInvestmentTransactionSellType:
      title: SellType
      description: Selling an investment
      type: string
      properties:
        distribution:
          type: string
          description: Outflow of assets from a tax-advantaged account
        exercise:
          type: string
          description: Exercise of an option or warrant contract
        sell:
          type: string
          description: Sell to close or decrease an existing holding
        sell short:
          type: string
          description: Sell to open a short position
 ```
 
 Is this valid openAPI v3? I can't seem to generate a client with another codegen tool.
